/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.softwarica00163111.views;

/**
 *
 * @author Bikas
 */
public class DashboardInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashboardInternalFrame
     */
    public DashboardInternalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_genre = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        btn_adventure = new javax.swing.JButton();
        btn_biography = new javax.swing.JButton();
        btn_fantasy = new javax.swing.JButton();
        btn_fiction = new javax.swing.JButton();
        btn_history = new javax.swing.JButton();
        btn_horror = new javax.swing.JButton();
        btn_nonFiction = new javax.swing.JButton();
        btn_sciFi = new javax.swing.JButton();
        btn_thriller = new javax.swing.JButton();
        lbl_bookGenre = new javax.swing.JLabel();
        panel_recent = new javax.swing.JPanel();

        panel_genre.setBackground(new java.awt.Color(0, 51, 51));

        txt_search.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txt_search.setForeground(new java.awt.Color(0, 51, 153));

        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/softwarica00163111/icons/search.png"))); // NOI18N

        btn_adventure.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_adventure.setForeground(new java.awt.Color(0, 0, 102));
        btn_adventure.setText("Adventure");

        btn_biography.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_biography.setForeground(new java.awt.Color(0, 0, 102));
        btn_biography.setText("Biography");
        btn_biography.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_biographyActionPerformed(evt);
            }
        });

        btn_fantasy.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_fantasy.setForeground(new java.awt.Color(0, 0, 102));
        btn_fantasy.setText("Fantasy");

        btn_fiction.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_fiction.setForeground(new java.awt.Color(0, 0, 102));
        btn_fiction.setText("Fiction");

        btn_history.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_history.setForeground(new java.awt.Color(0, 0, 102));
        btn_history.setText("History");

        btn_horror.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_horror.setForeground(new java.awt.Color(0, 0, 102));
        btn_horror.setText("Horror");

        btn_nonFiction.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_nonFiction.setForeground(new java.awt.Color(0, 0, 102));
        btn_nonFiction.setText("Non-Fiction");
        btn_nonFiction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nonFictionActionPerformed(evt);
            }
        });

        btn_sciFi.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_sciFi.setForeground(new java.awt.Color(0, 0, 102));
        btn_sciFi.setText("Sci-Fi");

        btn_thriller.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_thriller.setForeground(new java.awt.Color(0, 0, 102));
        btn_thriller.setText("Thriller");

        lbl_bookGenre.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        lbl_bookGenre.setForeground(new java.awt.Color(153, 153, 255));
        lbl_bookGenre.setText("Book Genre :");

        javax.swing.GroupLayout panel_genreLayout = new javax.swing.GroupLayout(panel_genre);
        panel_genre.setLayout(panel_genreLayout);
        panel_genreLayout.setHorizontalGroup(
            panel_genreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_genreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_genreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_biography, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_adventure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_fantasy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_fiction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_history, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_horror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_nonFiction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_sciFi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_thriller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel_genreLayout.createSequentialGroup()
                        .addComponent(txt_search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(panel_genreLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lbl_bookGenre)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        panel_genreLayout.setVerticalGroup(
            panel_genreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_genreLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_genreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_bookGenre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_adventure)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_biography)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_fantasy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_fiction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_history)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_horror)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_nonFiction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_sciFi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_thriller)
                .addContainerGap(144, Short.MAX_VALUE))
        );

        panel_recent.setBackground(new java.awt.Color(0, 51, 51));
        panel_recent.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Recently Added", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Cooper Black", 0, 24), new java.awt.Color(153, 153, 255))); // NOI18N

        javax.swing.GroupLayout panel_recentLayout = new javax.swing.GroupLayout(panel_recent);
        panel_recent.setLayout(panel_recentLayout);
        panel_recentLayout.setHorizontalGroup(
            panel_recentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 957, Short.MAX_VALUE)
        );
        panel_recentLayout.setVerticalGroup(
            panel_recentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_genre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_recent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_genre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_recent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_biographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_biographyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_biographyActionPerformed

    private void btn_nonFictionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nonFictionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_nonFictionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_adventure;
    private javax.swing.JButton btn_biography;
    private javax.swing.JButton btn_fantasy;
    private javax.swing.JButton btn_fiction;
    private javax.swing.JButton btn_history;
    private javax.swing.JButton btn_horror;
    private javax.swing.JButton btn_nonFiction;
    private javax.swing.JButton btn_sciFi;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_thriller;
    private javax.swing.JLabel lbl_bookGenre;
    private javax.swing.JPanel panel_genre;
    private javax.swing.JPanel panel_recent;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
