/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.softwarica00163111.views;

import edu.softwarica00163111.controller.UserController;
import edu.softwarica00163111.model.User;
import javax.swing.JOptionPane;

/**
 *
 * @author Bikas
 */
public class EditSystemProfile extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditSystemProfile
     */
    public EditSystemProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pan_systemedit = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        lbl_confirmpassword = new javax.swing.JLabel();
        passfield = new javax.swing.JPasswordField();
        confirmpassfield = new javax.swing.JPasswordField();
        btn_ok = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        pan_systemedit.setBackground(new java.awt.Color(0, 51, 51));
        pan_systemedit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit System Profile", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Cooper Black", 1, 24), new java.awt.Color(153, 153, 255))); // NOI18N

        lbl_username.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(51, 153, 0));
        lbl_username.setText("Username :");

        txt_username.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        txt_username.setForeground(new java.awt.Color(0, 51, 153));

        lbl_password.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        lbl_password.setForeground(new java.awt.Color(51, 153, 0));
        lbl_password.setText("Password :");

        lbl_confirmpassword.setFont(new java.awt.Font("Hobo Std", 0, 24)); // NOI18N
        lbl_confirmpassword.setForeground(new java.awt.Color(51, 153, 0));
        lbl_confirmpassword.setText("Confirm Password :");

        passfield.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        passfield.setForeground(new java.awt.Color(0, 51, 153));

        confirmpassfield.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        confirmpassfield.setForeground(new java.awt.Color(0, 51, 153));

        btn_ok.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_ok.setForeground(new java.awt.Color(0, 0, 102));
        btn_ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/softwarica00163111/icons/ok.png"))); // NOI18N
        btn_ok.setText("OK");
        btn_ok.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(0, 0, 102));
        btn_reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/softwarica00163111/icons/Reset.png"))); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_cancel.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_cancel.setForeground(new java.awt.Color(0, 0, 102));
        btn_cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/softwarica00163111/icons/Cancel.png"))); // NOI18N
        btn_cancel.setText("Cancel");
        btn_cancel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pan_systemeditLayout = new javax.swing.GroupLayout(pan_systemedit);
        pan_systemedit.setLayout(pan_systemeditLayout);
        pan_systemeditLayout.setHorizontalGroup(
            pan_systemeditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_systemeditLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pan_systemeditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pan_systemeditLayout.createSequentialGroup()
                        .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btn_cancel)
                        .addGap(34, 34, 34))
                    .addGroup(pan_systemeditLayout.createSequentialGroup()
                        .addGroup(pan_systemeditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_confirmpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(lbl_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(pan_systemeditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_username)
                            .addComponent(passfield)
                            .addComponent(confirmpassfield, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pan_systemeditLayout.setVerticalGroup(
            pan_systemeditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pan_systemeditLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pan_systemeditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_username, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pan_systemeditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passfield, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lbl_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pan_systemeditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_confirmpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmpassfield, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(pan_systemeditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(btn_reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_systemedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pan_systemedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        String username = txt_username.getText();
        String password = String.valueOf(passfield.getPassword());
        String confirmpassword = String.valueOf(confirmpassfield.getPassword());
        if (!username.isEmpty()) {
            if (!password.isEmpty()) {
                if (!confirmpassword.isEmpty()) {
                    if (password.equals(confirmpassword)) {
                        User um = new User();
                        um.setUsername(username);
                        um.setPassword(password);
                        UserController uc = new UserController();
                        int isUserUpdated = uc.updateUser(um);
                        if (isUserUpdated == 1) {
                            JOptionPane.showMessageDialog(this, "Edited Successfully !");
                            txt_username.setText("");
                            passfield.setText("");
                            confirmpassfield.setText("");
                            txt_username.requestFocus();
                        } else {
                            JOptionPane.showMessageDialog(this, "There was a problem editing system profile !");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Passwords did not match !");
                        passfield.setText("");
                        confirmpassfield.setText("");
                        passfield.requestFocus();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Re-enter password !");
                    confirmpassfield.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please enter password !");
                passfield.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter username !");
            txt_username.requestFocus();
        }
    }//GEN-LAST:event_btn_okActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        txt_username.setText("");
        passfield.setText("");
        confirmpassfield.setText("");
        txt_username.requestFocus();
    }//GEN-LAST:event_btn_resetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_reset;
    private javax.swing.JPasswordField confirmpassfield;
    private javax.swing.JLabel lbl_confirmpassword;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPanel pan_systemedit;
    private javax.swing.JPasswordField passfield;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
