/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.softwarica00163111.views;

import edu.softwarica00163111.controller.CustomerController;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bikas
 */
public class ViewAllCustomers extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewAllVendors
     */
    private final CustomerController customercontroller;

    public ViewAllCustomers() {
        initComponents();
        customercontroller = new CustomerController();
        this.loadAllCustomers();
        addInternalFrameListener(new InternalFrameAdapter() {
            public void internalFrameClosing(InternalFrameEvent e) {
                DashboardInternalFrame dif = new DashboardInternalFrame();
                dif.setVisible(true);
                getParent().add(dif);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_viewAllCustomers = new javax.swing.JTable();
        panel = new javax.swing.JPanel();

        setClosable(true);

        tbl_viewAllCustomers.setBackground(new java.awt.Color(204, 255, 204));
        tbl_viewAllCustomers.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tbl_viewAllCustomers.setForeground(new java.awt.Color(0, 51, 153));
        tbl_viewAllCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Address", "Contact no.", "Book Purchased", "Purchase Date", "Quantity", "Rate (in Rs.)", "Discount (in %)", "Total Amount (in Rs.)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_viewAllCustomers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_viewAllCustomers.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_viewAllCustomers);
        if (tbl_viewAllCustomers.getColumnModel().getColumnCount() > 0) {
            tbl_viewAllCustomers.getColumnModel().getColumn(0).setPreferredWidth(500);
            tbl_viewAllCustomers.getColumnModel().getColumn(1).setPreferredWidth(500);
            tbl_viewAllCustomers.getColumnModel().getColumn(2).setPreferredWidth(500);
            tbl_viewAllCustomers.getColumnModel().getColumn(3).setPreferredWidth(500);
            tbl_viewAllCustomers.getColumnModel().getColumn(4).setPreferredWidth(400);
            tbl_viewAllCustomers.getColumnModel().getColumn(5).setPreferredWidth(250);
            tbl_viewAllCustomers.getColumnModel().getColumn(6).setPreferredWidth(250);
            tbl_viewAllCustomers.getColumnModel().getColumn(7).setPreferredWidth(250);
            tbl_viewAllCustomers.getColumnModel().getColumn(8).setPreferredWidth(250);
        }

        panel.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2269, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 55, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2269, Short.MAX_VALUE)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadAllCustomers() {
        ResultSet rs;
        try {
            rs = customercontroller.viewAllCustomer();
            while (rs.next()) {
                Object obj[] = {rs.getString("Name"), rs.getString("Address"), rs.getString("ContactNo"), rs.getString("BookPurchased"), rs.getString("PurchaseDate"), rs.getInt("Quantity"), rs.getFloat("Rate"), rs.getFloat("Discount"), rs.getFloat("TotalAmount")};
                DefaultTableModel dtm = (DefaultTableModel) tbl_viewAllCustomers.getModel();
                dtm.addRow(obj);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tbl_viewAllCustomers;
    // End of variables declaration//GEN-END:variables
}
