/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.softwarica00163111.views;

import edu.softwarica00163111.controller.OrderController;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bikas
 */
public class ViewAllOrders extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewAllVendors
     */
    private OrderController ordercontroller;

    public ViewAllOrders() {
        initComponents();
        ordercontroller = new OrderController();
        this.loadAllOrders();
        addInternalFrameListener(new InternalFrameAdapter() {
            public void internalFrameClosing(InternalFrameEvent e) {
                DashboardInternalFrame dif = new DashboardInternalFrame();
                dif.setVisible(true);
                getParent().add(dif);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_viewAllOrders = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        btn_edit = new javax.swing.JButton();
        btn_cancelOrder = new javax.swing.JButton();

        setClosable(true);

        tbl_viewAllOrders.setBackground(new java.awt.Color(204, 255, 204));
        tbl_viewAllOrders.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tbl_viewAllOrders.setForeground(new java.awt.Color(0, 51, 153));
        tbl_viewAllOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Address", "Contact no.", "Book Ordered", "Author", "Quantity", "Order Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_viewAllOrders.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbl_viewAllOrders.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_viewAllOrders);
        if (tbl_viewAllOrders.getColumnModel().getColumnCount() > 0) {
            tbl_viewAllOrders.getColumnModel().getColumn(0).setPreferredWidth(500);
            tbl_viewAllOrders.getColumnModel().getColumn(1).setPreferredWidth(500);
            tbl_viewAllOrders.getColumnModel().getColumn(2).setPreferredWidth(500);
            tbl_viewAllOrders.getColumnModel().getColumn(3).setPreferredWidth(500);
            tbl_viewAllOrders.getColumnModel().getColumn(4).setPreferredWidth(500);
            tbl_viewAllOrders.getColumnModel().getColumn(5).setPreferredWidth(250);
            tbl_viewAllOrders.getColumnModel().getColumn(6).setPreferredWidth(400);
        }

        panel.setBackground(new java.awt.Color(0, 51, 51));

        btn_edit.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(0, 0, 102));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/softwarica00163111/icons/edit.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_cancelOrder.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        btn_cancelOrder.setForeground(new java.awt.Color(0, 0, 102));
        btn_cancelOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/softwarica00163111/icons/cancel.png"))); // NOI18N
        btn_cancelOrder.setText("Cancel Order");
        btn_cancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_cancelOrder)
                .addGap(18, 18, 18)
                .addComponent(btn_edit)
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_edit)
                    .addComponent(btn_cancelOrder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 2269, Short.MAX_VALUE)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        /*int row = tbl_viewAllOrders.getSelectedRow();
         if (row >= 0) {
         String vendorName = (String) tbl_viewAllOrders.getModel().getValueAt(row, 0);
         String bookPurchased = (String) tbl_viewAllOrders.getModel().getValueAt(row, 4);
         //JOptionPane.showMessageDialog(this, "Vendor Name : " + vendorName + " Book Purchased : " + bookPurchased);
         //EditVendor editvendor = new EditVendor(vendorName, bookPurchased);
         ResultSet rs = vendorcontroller.editVendor(vendorName, bookPurchased);
         EditVendor editvendor = new EditVendor(rs);
         this.dispose();
         } else {
         JOptionPane.showMessageDialog(this, "No vendor selected ! Please select a vendor.");
         }*/
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_cancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelOrderActionPerformed
        int row = tbl_viewAllOrders.getSelectedRow();
        if (row >= 0) {
            String customerName = (String) tbl_viewAllOrders.getModel().getValueAt(row, 0);
            String bookOrdered = (String) tbl_viewAllOrders.getModel().getValueAt(row, 3);
            int deleteOrder = ordercontroller.cancelOrder(customerName, bookOrdered);
            if (deleteOrder == 1) {
                JOptionPane.showMessageDialog(this, "Order cancelled !");
                DefaultTableModel model = (DefaultTableModel) tbl_viewAllOrders.getModel();
                model.removeRow(row);
            } else {
                JOptionPane.showMessageDialog(this, "There was a problem cancelling the order !");
            }
        } else {
            JOptionPane.showMessageDialog(this, "No order selected ! Please select an order.");
        }
    }//GEN-LAST:event_btn_cancelOrderActionPerformed

    public void loadAllOrders() {
        ResultSet rs;
        try {
            rs = ordercontroller.viewAllOrder();
            while (rs.next()) {
                Object obj[] = {rs.getString("CustomerName"), rs.getString("Address"), rs.getString("ContactNo"), rs.getString("BookOrdered"), rs.getString("Author"), rs.getInt("Quantity"), rs.getString("OrderDate")};
                DefaultTableModel dtm = (DefaultTableModel) tbl_viewAllOrders.getModel();
                dtm.addRow(obj);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelOrder;
    private javax.swing.JButton btn_edit;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JTable tbl_viewAllOrders;
    // End of variables declaration//GEN-END:variables
}
