/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.softwarica00163111.views;

import edu.softwarica00163111.controller.VendorController;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bikas
 */
public class ViewAllVendors extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewAllVendors
     */
    private final VendorController vc;

    public ViewAllVendors() {
        initComponents();
        vc = new VendorController();
        this.loadAllVendors();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_viewAllVendors = new javax.swing.JTable();

        setClosable(true);

        tbl_viewAllVendors.setBackground(new java.awt.Color(204, 255, 204));
        tbl_viewAllVendors.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        tbl_viewAllVendors.setForeground(new java.awt.Color(255, 0, 0));
        tbl_viewAllVendors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vendor Name", "Address", "Contact no.", "Email", "Book Purchased", "Author", "Purchase Date", "Quantity", "Rate (in Rs.)", "Discount (in %)", "Total Amount (in Rs.)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_viewAllVendors.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tbl_viewAllVendors);
        if (tbl_viewAllVendors.getColumnModel().getColumnCount() > 0) {
            tbl_viewAllVendors.getColumnModel().getColumn(0).setPreferredWidth(500);
            tbl_viewAllVendors.getColumnModel().getColumn(1).setPreferredWidth(500);
            tbl_viewAllVendors.getColumnModel().getColumn(2).setPreferredWidth(500);
            tbl_viewAllVendors.getColumnModel().getColumn(3).setPreferredWidth(500);
            tbl_viewAllVendors.getColumnModel().getColumn(4).setPreferredWidth(500);
            tbl_viewAllVendors.getColumnModel().getColumn(5).setPreferredWidth(500);
            tbl_viewAllVendors.getColumnModel().getColumn(6).setPreferredWidth(400);
            tbl_viewAllVendors.getColumnModel().getColumn(7).setPreferredWidth(250);
            tbl_viewAllVendors.getColumnModel().getColumn(8).setPreferredWidth(250);
            tbl_viewAllVendors.getColumnModel().getColumn(9).setPreferredWidth(250);
            tbl_viewAllVendors.getColumnModel().getColumn(10).setPreferredWidth(250);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 2090, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void loadAllVendors() {
        ResultSet rs;
        try {
            rs = vc.viewAllVendor();
            while (rs.next()) {
                Object obj[] = {rs.getString("Name"), rs.getString("Address"), rs.getString("ContactNo"), rs.getString("Email"), rs.getString("BookPurchased"), rs.getString("Author"), rs.getString("PurchasedDate"), rs.getInt("Quantity"), rs.getFloat("Rate"), rs.getFloat("Discount"), rs.getFloat("TotalAmount")};
                DefaultTableModel dtm = (DefaultTableModel) tbl_viewAllVendors.getModel();
                dtm.addRow(obj);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_viewAllVendors;
    // End of variables declaration//GEN-END:variables
}
